# Main TOML config file for radio daemon
[info]
name = "Test Radio Daemon"
desc = "Radio daemon for testing and development"

[network]
ip = "0.0.0.0"
port = 8801

# Radio control configuration
[radio]
type = "sb9600"   # valid options are "none", "sb9600", and "cm108"
rxOnly = false

[none]
zone = "RX Only Zone Name"
chan = "RX Only Channel Name"

[sb9600]
head = "W9"     # head type (O5, M3, or W9)
port = "/dev/ttyUSB0"  # serial port for serial control

# Configure your audio devices here
# Run `daemon list-audio` to get the proper names/paths for your audio devices
[audio]
txDevice = "C-Media USB Headphone Set, USB Audio"
rxDevice = "C-Media USB Headphone Set, USB Audio"

# Text Lookups for zone/channel text
[lookups]
zoneLookup = [
	["Match", "Replace"],
	["Z", "Test Zone Name"]
]
chanLookup = [
	["IAA P25", "N9IAA VHF P25"],
	["N9IAA WX", "N9IAA Simulcast"]
]