# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Daemon for Linux & Windows

on:
  workflow_dispatch
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:

  build:
    name: Build
    strategy:
      matrix:
        runtime: [linux-x64, linux-arm64, win-x64]
    runs-on: ubuntu-latest
    env:
      DAEMON_PATH: daemon-${{ matrix.runtime }}
      DAEMON_SRC_PATH: ./daemon
    steps:
      # Checkout repo with recursive submodules
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.setup.outputs.VERSION }}
          submodules: recursive
      # Setup dotnet environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      # Restore deps
      - name: Restore dependencies
        working-directory: ${{ env.DAEMON_SRC_PATH }}
        run: dotnet restore
      # Build & publish the daemon
      - name: Build and Publish
        working-directory: ${{ env.DAEMON_SRC_PATH }}
        run: dotnet publish -c Release -r ${{ matrix.runtime }} --self-contained true
      # Package
      - name: Package
        run: |
          mkdir ${DAEMON_PATH}
          cp -r ${DAEMON_SRC_PATH}/bin/Release/net8.0/${{ matrix.runtime }}/publish/* "${DAEMON_PATH}"
          (cd ${DAEMON_PATH}; zip -r ../${DAEMON_PATH}.zip ./*)
      # Upload
      - name: Upload Daemon Artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: ${{ env.DAEMON_PATH }}
          path: ${{ env.DAEMON_PATH }}.zip
          if-no-files-found: error
      
